groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 100
    profile_acceleration: 25
    torque_enable: true

singles:
  gripper:
    operating_mode: pwm
    torque_enable: true
